# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\OneDrive - connect.hku.hk\25-Python Program\1-Rabi\Examples\Widefield\GUI\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1900, 1010)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_Camera = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Camera.setGeometry(QtCore.QRect(10, 10, 532, 960))
        self.groupBox_Camera.setObjectName("groupBox_Camera")
        self.groupBox_Run = QtWidgets.QGroupBox(self.groupBox_Camera)
        self.groupBox_Run.setGeometry(QtCore.QRect(10, 500, 512, 141))
        self.groupBox_Run.setObjectName("groupBox_Run")
        self.pushButton_Submit = QtWidgets.QPushButton(self.groupBox_Run)
        self.pushButton_Submit.setGeometry(QtCore.QRect(10, 30, 75, 23))
        self.pushButton_Submit.setObjectName("pushButton_Submit")
        self.pushButton_Stop = QtWidgets.QPushButton(self.groupBox_Run)
        self.pushButton_Stop.setGeometry(QtCore.QRect(100, 30, 75, 23))
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.pushButton_Single = QtWidgets.QPushButton(self.groupBox_Run)
        self.pushButton_Single.setGeometry(QtCore.QRect(190, 30, 75, 23))
        self.pushButton_Single.setObjectName("pushButton_Single")
        self.pushButton_Save_Camera = QtWidgets.QPushButton(self.groupBox_Run)
        self.pushButton_Save_Camera.setGeometry(QtCore.QRect(430, 80, 75, 23))
        self.pushButton_Save_Camera.setObjectName("pushButton_Save_Camera")
        self.pushButton_SavePath = QtWidgets.QPushButton(self.groupBox_Run)
        self.pushButton_SavePath.setGeometry(QtCore.QRect(350, 80, 75, 23))
        self.pushButton_SavePath.setObjectName("pushButton_SavePath")
        self.lineEdit_Camera_SavePath = QtWidgets.QLineEdit(self.groupBox_Run)
        self.lineEdit_Camera_SavePath.setGeometry(QtCore.QRect(10, 80, 331, 20))
        self.lineEdit_Camera_SavePath.setText("")
        self.lineEdit_Camera_SavePath.setObjectName("lineEdit_Camera_SavePath")
        self.pushButton_LoadFrame = QtWidgets.QPushButton(self.groupBox_Run)
        self.pushButton_LoadFrame.setGeometry(QtCore.QRect(280, 30, 75, 23))
        self.pushButton_LoadFrame.setObjectName("pushButton_LoadFrame")
        self.pushButton_Play = QtWidgets.QPushButton(self.groupBox_Run)
        self.pushButton_Play.setGeometry(QtCore.QRect(370, 30, 75, 23))
        self.pushButton_Play.setObjectName("pushButton_Play")
        self.label_12 = QtWidgets.QLabel(self.groupBox_Run)
        self.label_12.setGeometry(QtCore.QRect(10, 110, 54, 12))
        self.label_12.setObjectName("label_12")
        self.lineEdit_FileName = QtWidgets.QLineEdit(self.groupBox_Run)
        self.lineEdit_FileName.setGeometry(QtCore.QRect(80, 110, 113, 20))
        self.lineEdit_FileName.setObjectName("lineEdit_FileName")
        self.label_31 = QtWidgets.QLabel(self.groupBox_Run)
        self.label_31.setGeometry(QtCore.QRect(340, 105, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.groupBox_Parameters = QtWidgets.QGroupBox(self.groupBox_Camera)
        self.groupBox_Parameters.setGeometry(QtCore.QRect(10, 640, 511, 51))
        self.groupBox_Parameters.setObjectName("groupBox_Parameters")
        self.label_ExposureTime = QtWidgets.QLabel(self.groupBox_Parameters)
        self.label_ExposureTime.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.label_ExposureTime.setObjectName("label_ExposureTime")
        self.lineEdit_ExposureTime = QtWidgets.QLineEdit(self.groupBox_Parameters)
        self.lineEdit_ExposureTime.setGeometry(QtCore.QRect(130, 20, 51, 20))
        self.lineEdit_ExposureTime.setMouseTracking(True)
        self.lineEdit_ExposureTime.setObjectName("lineEdit_ExposureTime")
        self.lineEdit_left_up_x = QtWidgets.QLineEdit(self.groupBox_Camera)
        self.lineEdit_left_up_x.setGeometry(QtCore.QRect(100, 770, 41, 20))
        self.lineEdit_left_up_x.setObjectName("lineEdit_left_up_x")
        self.lineEdit_left_up_y = QtWidgets.QLineEdit(self.groupBox_Camera)
        self.lineEdit_left_up_y.setGeometry(QtCore.QRect(150, 770, 41, 20))
        self.lineEdit_left_up_y.setObjectName("lineEdit_left_up_y")
        self.label_26 = QtWidgets.QLabel(self.groupBox_Camera)
        self.label_26.setGeometry(QtCore.QRect(30, 770, 61, 20))
        self.label_26.setAutoFillBackground(True)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_Camera)
        self.label_27.setGeometry(QtCore.QRect(30, 800, 61, 20))
        self.label_27.setObjectName("label_27")
        self.lineEdit_right_down_x = QtWidgets.QLineEdit(self.groupBox_Camera)
        self.lineEdit_right_down_x.setEnabled(True)
        self.lineEdit_right_down_x.setGeometry(QtCore.QRect(100, 800, 41, 20))
        self.lineEdit_right_down_x.setObjectName("lineEdit_right_down_x")
        self.lineEdit_right_down_y = QtWidgets.QLineEdit(self.groupBox_Camera)
        self.lineEdit_right_down_y.setGeometry(QtCore.QRect(150, 800, 41, 20))
        self.lineEdit_right_down_y.setObjectName("lineEdit_right_down_y")
        self.label_28 = QtWidgets.QLabel(self.groupBox_Camera)
        self.label_28.setGeometry(QtCore.QRect(120, 750, 21, 16))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_Camera)
        self.label_29.setGeometry(QtCore.QRect(170, 750, 21, 16))
        self.label_29.setObjectName("label_29")
        self.radioButton_ALL = QtWidgets.QRadioButton(self.groupBox_Camera)
        self.radioButton_ALL.setGeometry(QtCore.QRect(30, 720, 89, 16))
        self.radioButton_ALL.setObjectName("radioButton_ALL")
        self.radioButton_Customized = QtWidgets.QRadioButton(self.groupBox_Camera)
        self.radioButton_Customized.setGeometry(QtCore.QRect(90, 720, 89, 16))
        self.radioButton_Customized.setObjectName("radioButton_Customized")
        self.label_30 = QtWidgets.QLabel(self.groupBox_Camera)
        self.label_30.setGeometry(QtCore.QRect(30, 747, 61, 20))
        self.label_30.setObjectName("label_30")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_Camera)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 690, 511, 151))
        self.groupBox_6.setObjectName("groupBox_6")
        self.pushButton_pb_on = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_pb_on.setGeometry(QtCore.QRect(360, 90, 61, 23))
        self.pushButton_pb_on.setObjectName("pushButton_pb_on")
        self.Channels1 = QtWidgets.QLabel(self.groupBox_6)
        self.Channels1.setGeometry(QtCore.QRect(350, 60, 54, 12))
        self.Channels1.setObjectName("Channels1")
        self.pushButton_pb_off = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_pb_off.setGeometry(QtCore.QRect(434, 90, 61, 23))
        self.pushButton_pb_off.setObjectName("pushButton_pb_off")
        self.lineEdit_pb_channels = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_pb_channels.setGeometry(QtCore.QRect(412, 60, 81, 20))
        self.lineEdit_pb_channels.setObjectName("lineEdit_pb_channels")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_Camera)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 850, 511, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.comboBox_ChannelPulsed = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_ChannelPulsed.setGeometry(QtCore.QRect(10, 20, 69, 22))
        self.comboBox_ChannelPulsed.setObjectName("comboBox_ChannelPulsed")
        self.comboBox_ChannelPulsed.addItem("")
        self.comboBox_ChannelPulsed.addItem("")
        self.comboBox_ChannelPulsed.addItem("")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(90, 20, 41, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(90, 50, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(90, 80, 54, 12))
        self.label_4.setObjectName("label_4")
        self.lineEdit_start_time = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_start_time.setGeometry(QtCore.QRect(150, 10, 61, 20))
        self.lineEdit_start_time.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_start_time.setObjectName("lineEdit_start_time")
        self.lineEdit_duration_time = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_duration_time.setGeometry(QtCore.QRect(150, 40, 61, 20))
        self.lineEdit_duration_time.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_duration_time.setObjectName("lineEdit_duration_time")
        self.lineEdit_stop_time = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_stop_time.setGeometry(QtCore.QRect(150, 70, 61, 20))
        self.lineEdit_stop_time.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_stop_time.setObjectName("lineEdit_stop_time")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(220, 10, 21, 16))
        self.label_5.setObjectName("label_5")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(220, 40, 21, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(220, 70, 21, 16))
        self.label_14.setObjectName("label_14")
        self.pushButton_submit = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_submit.setGeometry(QtCore.QRect(10, 60, 71, 23))
        self.pushButton_submit.setObjectName("pushButton_submit")
        self.lineEdit_start_scan = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_start_scan.setGeometry(QtCore.QRect(240, 10, 61, 20))
        self.lineEdit_start_scan.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_start_scan.setClearButtonEnabled(False)
        self.lineEdit_start_scan.setObjectName("lineEdit_start_scan")
        self.lineEdit_duration_scan = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_duration_scan.setGeometry(QtCore.QRect(240, 40, 61, 20))
        self.lineEdit_duration_scan.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_duration_scan.setObjectName("lineEdit_duration_scan")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_6.setGeometry(QtCore.QRect(240, 70, 61, 20))
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_clear_allchannel = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_clear_allchannel.setGeometry(QtCore.QRect(320, 70, 71, 23))
        self.pushButton_clear_allchannel.setObjectName("pushButton_clear_allchannel")
        self.pushButton_clear_channel = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_clear_channel.setGeometry(QtCore.QRect(320, 40, 71, 23))
        self.pushButton_clear_channel.setObjectName("pushButton_clear_channel")
        self.pushButton_repeat = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_repeat.setGeometry(QtCore.QRect(400, 40, 61, 23))
        self.pushButton_repeat.setObjectName("pushButton_repeat")
        self.pushButton_reset = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_reset.setGeometry(QtCore.QRect(400, 70, 61, 23))
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.lineEdit_RepetitionsPulsed = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_RepetitionsPulsed.setGeometry(QtCore.QRect(400, 10, 51, 20))
        self.lineEdit_RepetitionsPulsed.setObjectName("lineEdit_RepetitionsPulsed")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(320, 10, 71, 16))
        self.label_17.setObjectName("label_17")
        self.widget_Sequence = QtWidgets.QWidget(self.groupBox_Camera)
        self.widget_Sequence.setGeometry(QtCore.QRect(30, 10, 291, 191))
        self.widget_Sequence.setObjectName("widget_Sequence")
        self.groupBox_6.raise_()
        self.groupBox_Run.raise_()
        self.groupBox_Parameters.raise_()
        self.lineEdit_left_up_x.raise_()
        self.lineEdit_left_up_y.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.lineEdit_right_down_x.raise_()
        self.lineEdit_right_down_y.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.radioButton_ALL.raise_()
        self.radioButton_Customized.raise_()
        self.label_30.raise_()
        self.groupBox_3.raise_()
        self.widget_Sequence.raise_()
        self.groupBox_Analysis = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Analysis.setGeometry(QtCore.QRect(1290, 10, 600, 960))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_Analysis.setFont(font)
        self.groupBox_Analysis.setObjectName("groupBox_Analysis")
        self.widget_Counts = QtWidgets.QWidget(self.groupBox_Analysis)
        self.widget_Counts.setGeometry(QtCore.QRect(10, 10, 580, 300))
        self.widget_Counts.setObjectName("widget_Counts")
        self.groupBox_Hardware = QtWidgets.QGroupBox(self.groupBox_Analysis)
        self.groupBox_Hardware.setGeometry(QtCore.QRect(10, 390, 581, 301))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_Hardware.setFont(font)
        self.groupBox_Hardware.setObjectName("groupBox_Hardware")
        self.groupBox_Microwave = QtWidgets.QGroupBox(self.groupBox_Hardware)
        self.groupBox_Microwave.setGeometry(QtCore.QRect(180, 10, 391, 80))
        self.groupBox_Microwave.setObjectName("groupBox_Microwave")
        self.lineEdit_Power_Constant = QtWidgets.QLineEdit(self.groupBox_Microwave)
        self.lineEdit_Power_Constant.setGeometry(QtCore.QRect(110, 20, 81, 20))
        self.lineEdit_Power_Constant.setObjectName("lineEdit_Power_Constant")
        self.lineEdit_Frequency_Constant = QtWidgets.QLineEdit(self.groupBox_Microwave)
        self.lineEdit_Frequency_Constant.setGeometry(QtCore.QRect(110, 50, 81, 20))
        self.lineEdit_Frequency_Constant.setObjectName("lineEdit_Frequency_Constant")
        self.label_8 = QtWidgets.QLabel(self.groupBox_Microwave)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_Microwave)
        self.label_9.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_9.setObjectName("label_9")
        self.pushButton_MW_get = QtWidgets.QPushButton(self.groupBox_Microwave)
        self.pushButton_MW_get.setGeometry(QtCore.QRect(210, 20, 75, 23))
        self.pushButton_MW_get.setObjectName("pushButton_MW_get")
        self.pushButton_MW_set = QtWidgets.QPushButton(self.groupBox_Microwave)
        self.pushButton_MW_set.setGeometry(QtCore.QRect(210, 50, 75, 23))
        self.pushButton_MW_set.setObjectName("pushButton_MW_set")
        self.pushButton_MW_on = QtWidgets.QPushButton(self.groupBox_Microwave)
        self.pushButton_MW_on.setGeometry(QtCore.QRect(310, 20, 75, 23))
        self.pushButton_MW_on.setObjectName("pushButton_MW_on")
        self.pushButton_MW_off = QtWidgets.QPushButton(self.groupBox_Microwave)
        self.pushButton_MW_off.setGeometry(QtCore.QRect(310, 50, 75, 23))
        self.pushButton_MW_off.setObjectName("pushButton_MW_off")
        self.groupBox_Laser = QtWidgets.QGroupBox(self.groupBox_Hardware)
        self.groupBox_Laser.setGeometry(QtCore.QRect(10, 10, 171, 80))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_Laser.setFont(font)
        self.groupBox_Laser.setObjectName("groupBox_Laser")
        self.pushButton_laser_on = QtWidgets.QPushButton(self.groupBox_Laser)
        self.pushButton_laser_on.setGeometry(QtCore.QRect(10, 20, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_laser_on.setFont(font)
        self.pushButton_laser_on.setObjectName("pushButton_laser_on")
        self.pushButton_laser_off = QtWidgets.QPushButton(self.groupBox_Laser)
        self.pushButton_laser_off.setGeometry(QtCore.QRect(90, 20, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_laser_off.setFont(font)
        self.pushButton_laser_off.setObjectName("pushButton_laser_off")
        self.label = QtWidgets.QLabel(self.groupBox_Laser)
        self.label.setGeometry(QtCore.QRect(30, 50, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_laser_power = QtWidgets.QLineEdit(self.groupBox_Laser)
        self.lineEdit_laser_power.setGeometry(QtCore.QRect(92, 50, 71, 20))
        self.lineEdit_laser_power.setObjectName("lineEdit_laser_power")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_Hardware)
        self.groupBox_5.setGeometry(QtCore.QRect(290, 190, 281, 101))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setGeometry(QtCore.QRect(10, 60, 91, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_RS_current1 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_RS_current1.setGeometry(QtCore.QRect(80, 60, 51, 20))
        self.lineEdit_RS_current1.setObjectName("lineEdit_RS_current1")
        self.lineEdit_RS_voltage1 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_RS_voltage1.setGeometry(QtCore.QRect(80, 30, 51, 20))
        self.lineEdit_RS_voltage1.setObjectName("lineEdit_RS_voltage1")
        self.pushButton_RS_set1 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_RS_set1.setGeometry(QtCore.QRect(140, 30, 51, 51))
        self.pushButton_RS_set1.setObjectName("pushButton_RS_set1")
        self.pushButton_RS_on1 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_RS_on1.setGeometry(QtCore.QRect(200, 30, 75, 23))
        self.pushButton_RS_on1.setObjectName("pushButton_RS_on1")
        self.pushButton_RS_off1 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_RS_off1.setGeometry(QtCore.QRect(200, 60, 75, 23))
        self.pushButton_RS_off1.setObjectName("pushButton_RS_off1")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_Hardware)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 190, 281, 101))
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_24 = QtWidgets.QLabel(self.groupBox_9)
        self.label_24.setGeometry(QtCore.QRect(10, 60, 91, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_9)
        self.label_25.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.label_25.setObjectName("label_25")
        self.lineEdit_RS_current = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_RS_current.setGeometry(QtCore.QRect(80, 60, 51, 20))
        self.lineEdit_RS_current.setObjectName("lineEdit_RS_current")
        self.lineEdit_Keithley_voltage = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_Keithley_voltage.setGeometry(QtCore.QRect(80, 30, 51, 20))
        self.lineEdit_Keithley_voltage.setObjectName("lineEdit_Keithley_voltage")
        self.pushButton_Keithley_set = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_Keithley_set.setGeometry(QtCore.QRect(140, 30, 51, 51))
        self.pushButton_Keithley_set.setObjectName("pushButton_Keithley_set")
        self.pushButton_Keithley_on = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_Keithley_on.setGeometry(QtCore.QRect(200, 30, 75, 23))
        self.pushButton_Keithley_on.setObjectName("pushButton_Keithley_on")
        self.pushButton_Keithley_off = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_Keithley_off.setGeometry(QtCore.QRect(200, 60, 75, 23))
        self.pushButton_Keithley_off.setObjectName("pushButton_Keithley_off")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_Analysis)
        self.groupBox.setGeometry(QtCore.QRect(10, 310, 581, 81))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_Clear = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Clear.setGeometry(QtCore.QRect(10, 30, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Clear.setFont(font)
        self.pushButton_Clear.setObjectName("pushButton_Clear")
        self.pushButton_LinePlot = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_LinePlot.setGeometry(QtCore.QRect(90, 30, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_LinePlot.setFont(font)
        self.pushButton_LinePlot.setObjectName("pushButton_LinePlot")
        self.pushButton_Histogram = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Histogram.setGeometry(QtCore.QRect(170, 30, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Histogram.setFont(font)
        self.pushButton_Histogram.setObjectName("pushButton_Histogram")
        self.pushButton_Save_Analysis = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Save_Analysis.setGeometry(QtCore.QRect(250, 30, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Save_Analysis.setFont(font)
        self.pushButton_Save_Analysis.setObjectName("pushButton_Save_Analysis")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(440, 20, 61, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(510, 20, 61, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_ = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_.setGeometry(QtCore.QRect(372, 20, 61, 20))
        self.lineEdit_.setObjectName("lineEdit_")
        self.listWidget_sequence = QtWidgets.QListWidget(self.groupBox_Analysis)
        self.listWidget_sequence.setGeometry(QtCore.QRect(10, 710, 581, 241))
        self.listWidget_sequence.setObjectName("listWidget_sequence")
        self.groupBox_PulsedExperiment = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_PulsedExperiment.setGeometry(QtCore.QRect(550, 10, 731, 960))
        self.groupBox_PulsedExperiment.setObjectName("groupBox_PulsedExperiment")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_PulsedExperiment)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 420, 711, 231))
        self.groupBox_10.setObjectName("groupBox_10")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_11.setGeometry(QtCore.QRect(650, 20, 61, 131))
        self.groupBox_11.setObjectName("groupBox_11")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 20, 31, 16))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 50, 31, 16))
        self.radioButton_3.setObjectName("radioButton_3")
        self.checkBox_AveragedPulsed = QtWidgets.QCheckBox(self.groupBox_10)
        self.checkBox_AveragedPulsed.setGeometry(QtCore.QRect(10, 160, 71, 16))
        self.checkBox_AveragedPulsed.setObjectName("checkBox_AveragedPulsed")
        self.checkBox_FitPulsed = QtWidgets.QCheckBox(self.groupBox_10)
        self.checkBox_FitPulsed.setGeometry(QtCore.QRect(90, 160, 71, 16))
        self.checkBox_FitPulsed.setObjectName("checkBox_FitPulsed")
        self.checkBox_SavePulsed = QtWidgets.QCheckBox(self.groupBox_10)
        self.checkBox_SavePulsed.setGeometry(QtCore.QRect(160, 160, 91, 16))
        self.checkBox_SavePulsed.setObjectName("checkBox_SavePulsed")
        self.checkBox_ = QtWidgets.QCheckBox(self.groupBox_10)
        self.checkBox_.setGeometry(QtCore.QRect(260, 160, 71, 16))
        self.checkBox_.setObjectName("checkBox_")
        self.label_18 = QtWidgets.QLabel(self.groupBox_10)
        self.label_18.setGeometry(QtCore.QRect(360, 160, 121, 16))
        self.label_18.setObjectName("label_18")
        self.lineEdit_NumberOfResonancePulsed = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_NumberOfResonancePulsed.setGeometry(QtCore.QRect(490, 160, 71, 20))
        self.lineEdit_NumberOfResonancePulsed.setObjectName("lineEdit_NumberOfResonancePulsed")
        self.lineEdit_SavePathPulsed = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_SavePathPulsed.setGeometry(QtCore.QRect(10, 190, 301, 20))
        self.lineEdit_SavePathPulsed.setObjectName("lineEdit_SavePathPulsed")
        self.pushButton_SavePulsed = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_SavePulsed.setGeometry(QtCore.QRect(400, 190, 75, 23))
        self.pushButton_SavePulsed.setObjectName("pushButton_SavePulsed")
        self.pushButton_SavePathPulsed = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_SavePathPulsed.setGeometry(QtCore.QRect(320, 190, 75, 23))
        self.pushButton_SavePathPulsed.setObjectName("pushButton_SavePathPulsed")
        self.pushButton_pulsed_start = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_pulsed_start.setGeometry(QtCore.QRect(480, 190, 75, 23))
        self.pushButton_pulsed_start.setObjectName("pushButton_pulsed_start")
        self.pushButton_Pulsed_Stop = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_Pulsed_Stop.setGeometry(QtCore.QRect(560, 190, 75, 23))
        self.pushButton_Pulsed_Stop.setObjectName("pushButton_Pulsed_Stop")
        self.lineEdit_loops = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_loops.setGeometry(QtCore.QRect(650, 160, 51, 20))
        self.lineEdit_loops.setObjectName("lineEdit_loops")
        self.label_15 = QtWidgets.QLabel(self.groupBox_10)
        self.label_15.setGeometry(QtCore.QRect(600, 160, 31, 16))
        self.label_15.setObjectName("label_15")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 20, 651, 131))
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton_CW_ODMR = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_CW_ODMR.setGeometry(QtCore.QRect(10, 20, 89, 16))
        self.radioButton_CW_ODMR.setObjectName("radioButton_CW_ODMR")
        self.radioButton_pulsed_ODMR = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_pulsed_ODMR.setGeometry(QtCore.QRect(10, 40, 89, 16))
        self.radioButton_pulsed_ODMR.setObjectName("radioButton_pulsed_ODMR")
        self.radioButton_Rabi = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_Rabi.setGeometry(QtCore.QRect(10, 60, 89, 16))
        self.radioButton_Rabi.setObjectName("radioButton_Rabi")
        self.radioButton_Delay_Time = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_Delay_Time.setGeometry(QtCore.QRect(10, 80, 89, 16))
        self.radioButton_Delay_Time.setObjectName("radioButton_Delay_Time")
        self.radioButton_ODMR_Versus_MW = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_ODMR_Versus_MW.setGeometry(QtCore.QRect(10, 100, 111, 16))
        self.radioButton_ODMR_Versus_MW.setObjectName("radioButton_ODMR_Versus_MW")
        self.pushButton_experiment_schemes = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_experiment_schemes.setGeometry(QtCore.QRect(560, 100, 75, 23))
        self.pushButton_experiment_schemes.setObjectName("pushButton_experiment_schemes")
        self.radioButton_calibration_delay_time = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_calibration_delay_time.setGeometry(QtCore.QRect(140, 20, 89, 16))
        self.radioButton_calibration_delay_time.setObjectName("radioButton_calibration_delay_time")
        self.widget_ODMR = QtWidgets.QWidget(self.groupBox_PulsedExperiment)
        self.widget_ODMR.setGeometry(QtCore.QRect(10, 20, 711, 321))
        self.widget_ODMR.setObjectName("widget_ODMR")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_PulsedExperiment)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 340, 711, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber_2.setGeometry(QtCore.QRect(120, 20, 101, 41))
        self.lcdNumber_2.setDigitCount(5)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.Loops = QtWidgets.QLCDNumber(self.groupBox_2)
        self.Loops.setGeometry(QtCore.QRect(10, 20, 101, 41))
        self.Loops.setDigitCount(5)
        self.Loops.setObjectName("Loops")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber_3.setGeometry(QtCore.QRect(230, 20, 101, 41))
        self.lcdNumber_3.setDigitCount(5)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber_4.setGeometry(QtCore.QRect(340, 20, 101, 41))
        self.lcdNumber_4.setDigitCount(5)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber_5.setGeometry(QtCore.QRect(450, 20, 101, 41))
        self.lcdNumber_5.setDigitCount(5)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber_6.setGeometry(QtCore.QRect(560, 20, 101, 41))
        self.lcdNumber_6.setDigitCount(5)
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.plainTextEdit_notes = QtWidgets.QPlainTextEdit(self.groupBox_PulsedExperiment)
        self.plainTextEdit_notes.setGeometry(QtCore.QRect(10, 660, 711, 131))
        self.plainTextEdit_notes.setPlainText("")
        self.plainTextEdit_notes.setObjectName("plainTextEdit_notes")
        self.pushButton_savenotes = QtWidgets.QPushButton(self.groupBox_PulsedExperiment)
        self.pushButton_savenotes.setGeometry(QtCore.QRect(640, 805, 75, 23))
        self.pushButton_savenotes.setObjectName("pushButton_savenotes")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_PulsedExperiment)
        self.groupBox_7.setGeometry(QtCore.QRect(400, 800, 221, 31))
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.radioButton_NoOverWrite = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_NoOverWrite.setGeometry(QtCore.QRect(110, 10, 89, 16))
        self.radioButton_NoOverWrite.setObjectName("radioButton_NoOverWrite")
        self.radioButton_OverWrite = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_OverWrite.setGeometry(QtCore.QRect(20, 10, 89, 16))
        self.radioButton_OverWrite.setChecked(True)
        self.radioButton_OverWrite.setObjectName("radioButton_OverWrite")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1900, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wide Field"))
        self.groupBox_Camera.setTitle(_translate("MainWindow", "Camera"))
        self.groupBox_Run.setTitle(_translate("MainWindow", "Run"))
        self.pushButton_Submit.setText(_translate("MainWindow", "Live"))
        self.pushButton_Stop.setText(_translate("MainWindow", "Stop"))
        self.pushButton_Single.setText(_translate("MainWindow", "Single"))
        self.pushButton_Save_Camera.setText(_translate("MainWindow", "Save"))
        self.pushButton_SavePath.setText(_translate("MainWindow", "Path"))
        self.pushButton_LoadFrame.setText(_translate("MainWindow", "Load Frame"))
        self.pushButton_Play.setText(_translate("MainWindow", "Play"))
        self.label_12.setText(_translate("MainWindow", "File_name"))
        self.label_31.setText(_translate("MainWindow", "Status Display Bar"))
        self.groupBox_Parameters.setTitle(_translate("MainWindow", "Parameters"))
        self.label_ExposureTime.setText(_translate("MainWindow", "Exposure Time (ms)"))
        self.lineEdit_ExposureTime.setText(_translate("MainWindow", "30"))
        self.label_26.setText(_translate("MainWindow", "Left Up"))
        self.label_27.setText(_translate("MainWindow", "Right Down"))
        self.label_28.setText(_translate("MainWindow", "X"))
        self.label_29.setText(_translate("MainWindow", "Y"))
        self.radioButton_ALL.setText(_translate("MainWindow", "ALL"))
        self.radioButton_Customized.setText(_translate("MainWindow", "Customized"))
        self.label_30.setText(_translate("MainWindow", "Rectangle"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Interested Range"))
        self.pushButton_pb_on.setText(_translate("MainWindow", "ON"))
        self.Channels1.setText(_translate("MainWindow", "Channels"))
        self.pushButton_pb_off.setText(_translate("MainWindow", "OFF"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Sequence"))
        self.comboBox_ChannelPulsed.setItemText(0, _translate("MainWindow", "Laser"))
        self.comboBox_ChannelPulsed.setItemText(1, _translate("MainWindow", "MW"))
        self.comboBox_ChannelPulsed.setItemText(2, _translate("MainWindow", "Camera"))
        self.label_2.setText(_translate("MainWindow", "Start"))
        self.label_3.setText(_translate("MainWindow", "Duration"))
        self.label_4.setText(_translate("MainWindow", "Stop"))
        self.lineEdit_start_time.setText(_translate("MainWindow", "0"))
        self.lineEdit_duration_time.setText(_translate("MainWindow", "0"))
        self.lineEdit_stop_time.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "ns"))
        self.label_13.setText(_translate("MainWindow", "ns"))
        self.label_14.setText(_translate("MainWindow", "ns"))
        self.pushButton_submit.setText(_translate("MainWindow", "Submit"))
        self.lineEdit_start_scan.setText(_translate("MainWindow", "0"))
        self.lineEdit_duration_scan.setText(_translate("MainWindow", "0"))
        self.lineEdit_6.setText(_translate("MainWindow", "Scan Step"))
        self.pushButton_clear_allchannel.setText(_translate("MainWindow", "Clear All"))
        self.pushButton_clear_channel.setText(_translate("MainWindow", "Clear"))
        self.pushButton_repeat.setText(_translate("MainWindow", "Repeat"))
        self.pushButton_reset.setText(_translate("MainWindow", "Reset"))
        self.label_17.setText(_translate("MainWindow", "Repetitions"))
        self.groupBox_Analysis.setTitle(_translate("MainWindow", "Analysis"))
        self.groupBox_Hardware.setTitle(_translate("MainWindow", "Hardware Panel"))
        self.groupBox_Microwave.setTitle(_translate("MainWindow", "Microwave"))
        self.label_8.setText(_translate("MainWindow", "Power (dBm)"))
        self.label_9.setText(_translate("MainWindow", "Frequency (Hz)"))
        self.pushButton_MW_get.setText(_translate("MainWindow", "Get"))
        self.pushButton_MW_set.setText(_translate("MainWindow", "Set"))
        self.pushButton_MW_on.setText(_translate("MainWindow", "ON"))
        self.pushButton_MW_off.setText(_translate("MainWindow", "OFF"))
        self.groupBox_Laser.setTitle(_translate("MainWindow", "Laser"))
        self.pushButton_laser_on.setText(_translate("MainWindow", "ON"))
        self.pushButton_laser_off.setText(_translate("MainWindow", "OFF"))
        self.label.setText(_translate("MainWindow", "Power"))
        self.groupBox_5.setTitle(_translate("MainWindow", "RS Power Supply"))
        self.label_10.setText(_translate("MainWindow", "Current (I)"))
        self.label_11.setText(_translate("MainWindow", "Voltage (V)"))
        self.pushButton_RS_set1.setText(_translate("MainWindow", "Set"))
        self.pushButton_RS_on1.setText(_translate("MainWindow", "CH1 ON"))
        self.pushButton_RS_off1.setText(_translate("MainWindow", "CH1 OFF"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Keithley Power Supply"))
        self.label_24.setText(_translate("MainWindow", "Current (I)"))
        self.label_25.setText(_translate("MainWindow", "Voltage (V)"))
        self.pushButton_Keithley_set.setText(_translate("MainWindow", "Set"))
        self.pushButton_Keithley_on.setText(_translate("MainWindow", "CH1 ON"))
        self.pushButton_Keithley_off.setText(_translate("MainWindow", "CH1 OFF"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.pushButton_Clear.setText(_translate("MainWindow", "Clear"))
        self.pushButton_LinePlot.setText(_translate("MainWindow", "Line Plot"))
        self.pushButton_Histogram.setText(_translate("MainWindow", "Histogram"))
        self.pushButton_Save_Analysis.setText(_translate("MainWindow", "Save"))
        self.groupBox_PulsedExperiment.setTitle(_translate("MainWindow", "Pulsed Experiment"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Control Panal"))
        self.groupBox_11.setTitle(_translate("MainWindow", "axis"))
        self.radioButton_2.setText(_translate("MainWindow", "X"))
        self.radioButton_3.setText(_translate("MainWindow", "Y"))
        self.checkBox_AveragedPulsed.setText(_translate("MainWindow", "Averaged"))
        self.checkBox_FitPulsed.setText(_translate("MainWindow", "Fit"))
        self.checkBox_SavePulsed.setText(_translate("MainWindow", "Save Frames"))
        self.checkBox_.setText(_translate("MainWindow", "CheckBox"))
        self.label_18.setText(_translate("MainWindow", "Number of Resonance"))
        self.pushButton_SavePulsed.setText(_translate("MainWindow", "Save"))
        self.pushButton_SavePathPulsed.setText(_translate("MainWindow", "Path"))
        self.pushButton_pulsed_start.setText(_translate("MainWindow", "Start"))
        self.pushButton_Pulsed_Stop.setText(_translate("MainWindow", "Stop"))
        self.label_15.setText(_translate("MainWindow", "Loops"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Experiment Schemes"))
        self.radioButton_CW_ODMR.setText(_translate("MainWindow", "CW ODMR"))
        self.radioButton_pulsed_ODMR.setText(_translate("MainWindow", "Pulsed ODMR"))
        self.radioButton_Rabi.setText(_translate("MainWindow", "Rabi"))
        self.radioButton_Delay_Time.setText(_translate("MainWindow", "Delay Time"))
        self.radioButton_ODMR_Versus_MW.setText(_translate("MainWindow", "ODMR Versus MW"))
        self.pushButton_experiment_schemes.setText(_translate("MainWindow", "Submit"))
        self.radioButton_calibration_delay_time.setText(_translate("MainWindow", "Calibration"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Information"))
        self.pushButton_savenotes.setText(_translate("MainWindow", "Save"))
        self.radioButton_NoOverWrite.setText(_translate("MainWindow", "NoOverWrite"))
        self.radioButton_OverWrite.setText(_translate("MainWindow", "OverWrite"))

