# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\rabi_programe\240729\rabi_data_processing\New_Rabi_data_GUI\GUI\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1061, 969)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mplwidget = QtWidgets.QWidget(self.centralwidget)
        self.mplwidget.setGeometry(QtCore.QRect(10, 10, 512, 512))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.mplwidget.setFont(font)
        self.mplwidget.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.mplwidget.setMouseTracking(True)
        self.mplwidget.setObjectName("mplwidget")
        self.tbwidget = QtWidgets.QWidget(self.centralwidget)
        self.tbwidget.setGeometry(QtCore.QRect(10, 520, 511, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.tbwidget.setFont(font)
        self.tbwidget.setObjectName("tbwidget")
        self.widget_row = QtWidgets.QWidget(self.centralwidget)
        self.widget_row.setGeometry(QtCore.QRect(10, 590, 821, 291))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.widget_row.setFont(font)
        self.widget_row.setObjectName("widget_row")
        self.tbwidget_row = QtWidgets.QWidget(self.centralwidget)
        self.tbwidget_row.setGeometry(QtCore.QRect(10, 880, 521, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.tbwidget_row.setFont(font)
        self.tbwidget_row.setObjectName("tbwidget_row")
        self.labelCCD = QtWidgets.QLabel(self.centralwidget)
        self.labelCCD.setGeometry(QtCore.QRect(530, 10, 512, 512))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.labelCCD.setFont(font)
        self.labelCCD.setText("")
        self.labelCCD.setObjectName("labelCCD")
        self.pushButton_reset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reset.setGeometry(QtCore.QRect(540, 530, 181, 46))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_reset.setFont(font)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.pushButton_show_rabi_in_roi = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_show_rabi_in_roi.setGeometry(QtCore.QRect(850, 530, 181, 46))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_show_rabi_in_roi.setFont(font)
        self.pushButton_show_rabi_in_roi.setObjectName("pushButton_show_rabi_in_roi")
        self.pushButton_fit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fit.setGeometry(QtCore.QRect(710, 890, 75, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_fit.setFont(font)
        self.pushButton_fit.setObjectName("pushButton_fit")
        self.pushButton_open = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open.setGeometry(QtCore.QRect(590, 890, 75, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_open.setFont(font)
        self.pushButton_open.setObjectName("pushButton_open")
        self.listWidget_fitting_results = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_fitting_results.setGeometry(QtCore.QRect(840, 590, 201, 291))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.listWidget_fitting_results.setFont(font)
        self.listWidget_fitting_results.setObjectName("listWidget_fitting_results")
        self.lineEdit_input_period = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_input_period.setGeometry(QtCore.QRect(950, 900, 91, 31))
        self.lineEdit_input_period.setObjectName("lineEdit_input_period")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(830, 900, 111, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1061, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Matplotlib Canvas"))
        self.pushButton_reset.setText(_translate("MainWindow", "Reset ROI"))
        self.pushButton_show_rabi_in_roi.setText(_translate("MainWindow", "Show Rabi in ROI"))
        self.pushButton_fit.setText(_translate("MainWindow", "Fit"))
        self.pushButton_open.setText(_translate("MainWindow", "Open File"))
        self.label.setText(_translate("MainWindow", "Fitting Period:"))

