# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\OneDrive - connect.hku.hk\25-Python Program\1-Rabi\Examples\Widefield\Sub_Windows\T1\GUI\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(803, 845)
        Dialog.setModal(True)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 761, 451))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 90, 741, 261))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_repetitions = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_repetitions.setGeometry(QtCore.QRect(470, 30, 61, 22))
        self.lineEdit_repetitions.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_repetitions.setObjectName("lineEdit_repetitions")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(40, 60, 53, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_AOM_duration = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_AOM_duration.setGeometry(QtCore.QRect(110, 60, 61, 22))
        self.lineEdit_AOM_duration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_AOM_duration.setObjectName("lineEdit_AOM_duration")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(380, 30, 71, 16))
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(120, 30, 51, 16))
        self.label_9.setObjectName("label_9")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(410, 90, 41, 20))
        self.label_14.setObjectName("label_14")
        self.lineEdit_gap_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_gap_2.setGeometry(QtCore.QRect(470, 90, 61, 22))
        self.lineEdit_gap_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_gap_2.setObjectName("lineEdit_gap_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(40, 130, 53, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_MW_duration = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_MW_duration.setGeometry(QtCore.QRect(110, 130, 61, 22))
        self.lineEdit_MW_duration.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_MW_duration.setObjectName("lineEdit_MW_duration")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(120, 100, 51, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(410, 60, 41, 20))
        self.label_18.setObjectName("label_18")
        self.lineEdit_gap_1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_gap_1.setGeometry(QtCore.QRect(470, 60, 61, 22))
        self.lineEdit_gap_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_gap_1.setObjectName("lineEdit_gap_1")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 170, 701, 80))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit_delay_sweep_start = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_delay_sweep_start.setGeometry(QtCore.QRect(80, 50, 61, 22))
        self.lineEdit_delay_sweep_start.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_delay_sweep_start.setObjectName("lineEdit_delay_sweep_start")
        self.lineEdit_delay_sweep_step = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_delay_sweep_step.setGeometry(QtCore.QRect(190, 50, 61, 22))
        self.lineEdit_delay_sweep_step.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_delay_sweep_step.setObjectName("lineEdit_delay_sweep_step")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(300, 20, 71, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_delay_sweep_end = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_delay_sweep_end.setGeometry(QtCore.QRect(300, 50, 61, 22))
        self.lineEdit_delay_sweep_end.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_delay_sweep_end.setObjectName("lineEdit_delay_sweep_end")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setGeometry(QtCore.QRect(190, 20, 71, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(70, 20, 81, 16))
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(420, 20, 71, 16))
        self.label_15.setObjectName("label_15")
        self.lineEdit_delay_sweep_number = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_delay_sweep_number.setGeometry(QtCore.QRect(420, 50, 61, 22))
        self.lineEdit_delay_sweep_number.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_delay_sweep_number.setObjectName("lineEdit_delay_sweep_number")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 741, 71))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(20, 30, 61, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_MW_freq = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_MW_freq.setGeometry(QtCore.QRect(310, 30, 71, 20))
        self.lineEdit_MW_freq.setObjectName("lineEdit_MW_freq")
        self.lineEdit_MW_power = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_MW_power.setGeometry(QtCore.QRect(90, 30, 71, 20))
        self.lineEdit_MW_power.setObjectName("lineEdit_MW_power")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(210, 30, 81, 16))
        self.label_11.setObjectName("label_11")
        self.label_status = QtWidgets.QLabel(self.groupBox)
        self.label_status.setGeometry(QtCore.QRect(10, 370, 511, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        self.pushButton_clear = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_clear.setGeometry(QtCore.QRect(560, 365, 81, 31))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_save = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_save.setGeometry(QtCore.QRect(660, 365, 81, 31))
        self.pushButton_save.setObjectName("pushButton_save")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.groupBox)
        self.buttonBox.setGeometry(QtCore.QRect(220, 410, 251, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_picture = QtWidgets.QLabel(Dialog)
        self.label_picture.setGeometry(QtCore.QRect(20, 470, 761, 341))
        self.label_picture.setText("")
        self.label_picture.setObjectName("label_picture")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "T1"))
        self.groupBox.setTitle(_translate("Dialog", "Control Panel"))
        self.groupBox_2.setTitle(_translate("Dialog", "Sequences"))
        self.lineEdit_repetitions.setText(_translate("Dialog", "12000"))
        self.label_3.setText(_translate("Dialog", "Laser"))
        self.lineEdit_AOM_duration.setText(_translate("Dialog", "2000"))
        self.label_10.setText(_translate("Dialog", "Repetitions"))
        self.label_9.setText(_translate("Dialog", "Duration"))
        self.label_14.setText(_translate("Dialog", "Gap 2"))
        self.lineEdit_gap_2.setText(_translate("Dialog", "500"))
        self.label_4.setText(_translate("Dialog", "MW"))
        self.lineEdit_MW_duration.setText(_translate("Dialog", "2000"))
        self.label_17.setText(_translate("Dialog", "Duration"))
        self.label_18.setText(_translate("Dialog", "Gap 1"))
        self.lineEdit_gap_1.setText(_translate("Dialog", "500"))
        self.groupBox_4.setTitle(_translate("Dialog", "Delay time"))
        self.lineEdit_delay_sweep_start.setText(_translate("Dialog", "0"))
        self.lineEdit_delay_sweep_step.setText(_translate("Dialog", "100"))
        self.label_7.setText(_translate("Dialog", "Sweep End"))
        self.lineEdit_delay_sweep_end.setText(_translate("Dialog", "2000"))
        self.label_12.setText(_translate("Dialog", "Sweep Step"))
        self.label_13.setText(_translate("Dialog", " Sweep Start"))
        self.label_15.setText(_translate("Dialog", "Number"))
        self.lineEdit_delay_sweep_number.setText(_translate("Dialog", "100"))
        self.groupBox_3.setTitle(_translate("Dialog", "MW Settings"))
        self.label_6.setText(_translate("Dialog", "Power(dBm)"))
        self.lineEdit_MW_freq.setText(_translate("Dialog", "2870000000"))
        self.lineEdit_MW_power.setText(_translate("Dialog", "0"))
        self.label_11.setText(_translate("Dialog", "Frequency(Hz)"))
        self.label_status.setText(_translate("Dialog", "TextLabel"))
        self.pushButton_clear.setText(_translate("Dialog", "Clear All"))
        self.pushButton_save.setText(_translate("Dialog", "Save"))

