# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\OneDrive - connect.hku.hk\17-工作内容\56-Nature Protocol\03-ODMR_analysis_ROI_20221007_InputFitParameters_BetterVersion\GUI\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1063, 1051)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mplwidget = QtWidgets.QWidget(self.centralwidget)
        self.mplwidget.setGeometry(QtCore.QRect(10, 10, 512, 512))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.mplwidget.setFont(font)
        self.mplwidget.setObjectName("mplwidget")
        self.tbwidget = QtWidgets.QWidget(self.centralwidget)
        self.tbwidget.setGeometry(QtCore.QRect(10, 530, 511, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.tbwidget.setFont(font)
        self.tbwidget.setObjectName("tbwidget")
        self.widget_row = QtWidgets.QWidget(self.centralwidget)
        self.widget_row.setGeometry(QtCore.QRect(10, 620, 511, 291))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.widget_row.setFont(font)
        self.widget_row.setObjectName("widget_row")
        self.tbwidget_row = QtWidgets.QWidget(self.centralwidget)
        self.tbwidget_row.setGeometry(QtCore.QRect(10, 920, 511, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.tbwidget_row.setFont(font)
        self.tbwidget_row.setObjectName("tbwidget_row")
        self.labelCCD = QtWidgets.QLabel(self.centralwidget)
        self.labelCCD.setGeometry(QtCore.QRect(540, 10, 512, 512))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.labelCCD.setFont(font)
        self.labelCCD.setText("")
        self.labelCCD.setObjectName("labelCCD")
        self.pushButton_reset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reset.setGeometry(QtCore.QRect(570, 525, 181, 46))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_reset.setFont(font)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.pushButton_show_odmr_in_roi = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_show_odmr_in_roi.setGeometry(QtCore.QRect(830, 525, 181, 46))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_show_odmr_in_roi.setFont(font)
        self.pushButton_show_odmr_in_roi.setObjectName("pushButton_show_odmr_in_roi")
        self.lineEdit_peak_num = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_peak_num.setGeometry(QtCore.QRect(680, 590, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_peak_num.setFont(font)
        self.lineEdit_peak_num.setObjectName("lineEdit_peak_num")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(560, 575, 111, 63))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.plainTextEdit_peak_position = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_peak_position.setGeometry(QtCore.QRect(680, 640, 371, 141))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.plainTextEdit_peak_position.setFont(font)
        self.plainTextEdit_peak_position.setObjectName("plainTextEdit_peak_position")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(950, 730, 111, 63))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_fit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fit.setGeometry(QtCore.QRect(540, 760, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_fit.setFont(font)
        self.pushButton_fit.setObjectName("pushButton_fit")
        self.pushButton_save_fit_result = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save_fit_result.setGeometry(QtCore.QRect(540, 880, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_save_fit_result.setFont(font)
        self.pushButton_save_fit_result.setObjectName("pushButton_save_fit_result")
        self.pushButton_select_peaks = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_select_peaks.setGeometry(QtCore.QRect(540, 640, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_select_peaks.setFont(font)
        self.pushButton_select_peaks.setObjectName("pushButton_select_peaks")
        self.pushButton_reset_peaks = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reset_peaks.setGeometry(QtCore.QRect(540, 820, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_reset_peaks.setFont(font)
        self.pushButton_reset_peaks.setObjectName("pushButton_reset_peaks")
        self.pushButton_undo_peaks = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_undo_peaks.setGeometry(QtCore.QRect(540, 700, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_undo_peaks.setFont(font)
        self.pushButton_undo_peaks.setObjectName("pushButton_undo_peaks")
        self.checkBox_manually_input_FWHM = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_manually_input_FWHM.setGeometry(QtCore.QRect(840, 580, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.checkBox_manually_input_FWHM.setFont(font)
        self.checkBox_manually_input_FWHM.setObjectName("checkBox_manually_input_FWHM")
        self.pushButton_open = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open.setGeometry(QtCore.QRect(977, 940, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.pushButton_open.setFont(font)
        self.pushButton_open.setObjectName("pushButton_open")
        self.lineEdit_Open_Path = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Open_Path.setGeometry(QtCore.QRect(540, 940, 431, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.lineEdit_Open_Path.setFont(font)
        self.lineEdit_Open_Path.setObjectName("lineEdit_Open_Path")
        self.listWidget_fitting_results = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_fitting_results.setGeometry(QtCore.QRect(680, 800, 371, 131))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.listWidget_fitting_results.setFont(font)
        self.listWidget_fitting_results.setObjectName("listWidget_fitting_results")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(950, 880, 111, 63))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1063, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Matplotlib Canvas"))
        self.pushButton_reset.setText(_translate("MainWindow", "Reset ROI"))
        self.pushButton_show_odmr_in_roi.setText(_translate("MainWindow", "Show ODMR in ROI"))
        self.label_4.setText(_translate("MainWindow", "Peaks Number"))
        self.label_5.setText(_translate("MainWindow", "Peaks Position"))
        self.pushButton_fit.setText(_translate("MainWindow", "Fit"))
        self.pushButton_save_fit_result.setText(_translate("MainWindow", "Save"))
        self.pushButton_select_peaks.setText(_translate("MainWindow", "Select Peaks"))
        self.pushButton_reset_peaks.setText(_translate("MainWindow", "Reset Peaks"))
        self.pushButton_undo_peaks.setText(_translate("MainWindow", "Undo Peaks"))
        self.checkBox_manually_input_FWHM.setText(_translate("MainWindow", "Manually Input FWHM"))
        self.pushButton_open.setText(_translate("MainWindow", "Open"))
        self.label_6.setText(_translate("MainWindow", "Fitting Results"))

