# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\OneDrive - connect.hku.hk\25-Python Program\12-Point_Spread_Function\GUI\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mplwidget = QtWidgets.QWidget(self.centralwidget)
        self.mplwidget.setGeometry(QtCore.QRect(0, 0, 512, 512))
        self.mplwidget.setObjectName("mplwidget")
        self.tbwidget = QtWidgets.QWidget(self.centralwidget)
        self.tbwidget.setGeometry(QtCore.QRect(0, 510, 511, 51))
        self.tbwidget.setObjectName("tbwidget")
        self.widget_row = QtWidgets.QWidget(self.centralwidget)
        self.widget_row.setGeometry(QtCore.QRect(10, 590, 511, 291))
        self.widget_row.setObjectName("widget_row")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(560, 50, 241, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_up = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_up.setObjectName("pushButton_up")
        self.gridLayout.addWidget(self.pushButton_up, 0, 1, 1, 1)
        self.pushButton_left = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_left.setObjectName("pushButton_left")
        self.gridLayout.addWidget(self.pushButton_left, 1, 0, 1, 1)
        self.pushButton_right = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_right.setObjectName("pushButton_right")
        self.gridLayout.addWidget(self.pushButton_right, 1, 2, 1, 1)
        self.pushButton_down = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_down.setObjectName("pushButton_down")
        self.gridLayout.addWidget(self.pushButton_down, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.pushButton_fit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_fit.setObjectName("pushButton_fit")
        self.verticalLayout_2.addWidget(self.pushButton_fit)
        self.widget_col = QtWidgets.QWidget(self.centralwidget)
        self.widget_col.setGeometry(QtCore.QRect(540, 590, 511, 291))
        self.widget_col.setMouseTracking(False)
        self.widget_col.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_col.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget_col.setObjectName("widget_col")
        self.lineEdit_Open_Path = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Open_Path.setGeometry(QtCore.QRect(560, 20, 381, 20))
        self.lineEdit_Open_Path.setObjectName("lineEdit_Open_Path")
        self.pushButton_open = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open.setGeometry(QtCore.QRect(950, 20, 75, 23))
        self.pushButton_open.setObjectName("pushButton_open")
        self.tbwidget_row = QtWidgets.QWidget(self.centralwidget)
        self.tbwidget_row.setGeometry(QtCore.QRect(10, 880, 511, 51))
        self.tbwidget_row.setObjectName("tbwidget_row")
        self.widget = QtWidgets.QWidget(self.tbwidget_row)
        self.widget.setGeometry(QtCore.QRect(390, 0, 119, 51))
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit_FWHM1 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_FWHM1.setReadOnly(True)
        self.lineEdit_FWHM1.setObjectName("lineEdit_FWHM1")
        self.horizontalLayout_5.addWidget(self.lineEdit_FWHM1)
        self.tbwidget_col = QtWidgets.QWidget(self.centralwidget)
        self.tbwidget_col.setGeometry(QtCore.QRect(540, 880, 511, 51))
        self.tbwidget_col.setObjectName("tbwidget_col")
        self.widget1 = QtWidgets.QWidget(self.tbwidget_col)
        self.widget1.setGeometry(QtCore.QRect(390, 0, 119, 51))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.widget1)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.lineEdit_FWHM2 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_FWHM2.setReadOnly(True)
        self.lineEdit_FWHM2.setObjectName("lineEdit_FWHM2")
        self.horizontalLayout_8.addWidget(self.lineEdit_FWHM2)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(230, 570, 54, 12))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(750, 570, 81, 16))
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Matplotlib Canvas"))
        self.pushButton.setText(_translate("MainWindow", "Mark"))
        self.pushButton_2.setText(_translate("MainWindow", "Select"))
        self.pushButton_3.setText(_translate("MainWindow", "Reset"))
        self.pushButton_up.setText(_translate("MainWindow", "Up"))
        self.pushButton_left.setText(_translate("MainWindow", "<"))
        self.pushButton_right.setText(_translate("MainWindow", ">"))
        self.pushButton_down.setText(_translate("MainWindow", "Down"))
        self.label_2.setText(_translate("MainWindow", "  Row(y) "))
        self.label.setText(_translate("MainWindow", "Column(x)"))
        self.pushButton_fit.setText(_translate("MainWindow", "Fit"))
        self.pushButton_open.setText(_translate("MainWindow", "Open"))
        self.label_5.setText(_translate("MainWindow", "FWHM"))
        self.label_8.setText(_translate("MainWindow", "FWHM"))
        self.label_11.setText(_translate("MainWindow", "One Row"))
        self.label_12.setText(_translate("MainWindow", "One Column"))

